---
# Server configuration
server:
  port: 9095
  servlet.encoding.charset: UTF-8
  shutdown: graceful

  tomcat:
    mbeanregistry:
      enabled: true

name: sda_weather_service

info:
  requestInitiatorName: ${name}

logging:
  level:
    org:
      hibernate: ERROR
    root: ERROR
    org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl: ERROR

driver: org.h2.Driver
url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
user: sa
password: ""
dialect: org.hibernate.dialect.H2Dialect
show_sql: true
hibernate.hbm2ddl.auto: update


# Metrics configuration
endpoints:
  actuator:
    sensitive: false
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: #"*"

  metrics:
    tags:
      application: ${name}
